### ISSUE TITLE
disabled dates are not working properly

### ISSUE THREAD

**Issue by f24aalam** [codesthq/vuelendar#33]
Hi, I am using your calendar component for one of my project, but it seems that the disabled-dates props are not working properly, it is disabling only "to" date

`<v-range-selector :start-date.sync="range.start" :end-date.sync="range.end" :disabledDates="{ to: '2020-02-24', from: '2020-02-12' }"/>`

this is the code which is I am using

**Comment by lusarz** [comment]
Hello, we changed API recently. Please try to use [isDisabled](https://github.com/codesthq/vuelendar/blob/master/components/vl-range-selector.vue#L33) prop. Example usage:

    <v-range-selector
       :is-disabled="date => date >= '2020-02-12' && date <= '2020-02-24' "
    />

**Comment by f24aalam** [comment]
Thank You Now its Working
