### ISSUE TITLE
Disabled Days not working for Range Selector

### ISSUE THREAD

**Issue by 5chub1** [codesthq/vuelendar#36]
When using the Range Selector the disabling of Dates is not working.

```
<v-range-selector
  :start-date.sync="range.start"
  :end-date.sync="range.end"
   disabled-dates="['2019-04-21', '2020-09-25']"
  ></v-range-selector>
```

![image](https://user-images.githubusercontent.com/40201325/89287406-356aa580-d654-11ea-8315-b511034fb0c2.png)

**Comment by lusarz** [comment]
Yes, `v-range-selector` doesn't support `disabled-dates` property. Please use `isDisabled: Function` property, like that:

```
<v-range-selector
  :start-date.sync="range.start"
  :end-date.sync="range.end"
   is-disabled="date => ['2019-04-21', '2020-09-25'].includes(date)"
/>
```

Please let me know if it works properly.

**Comment by 5chub1** [comment]
Hey @lusarz thanks for your fast reply. Unfortunately I can't get it to work with this method.

**Comment by lusarz** [comment]
@5chub1 I just checked it:
https://github.com/lusarz/vuelendar-demo/blob/bc5847cde77c67a12daf0abad37b03a223d6e3fa/src/App.vue#L4-L9

and it seems to works (1 and 3 August are disabled):
![Zrzut ekranu z 2020-08-05 10-41-02](https://user-images.githubusercontent.com/10059264/89392542-f5fe9080-d709-11ea-86c9-0918036e1c88.png)


You can check it yourself:
```
git clone git@github.com:lusarz/vuelendar-demo.git
git checkout disabled-demo
npm install
npm run start
```

**Comment by 5chub1** [comment]
Thank you for your help. It worked now. Unfortunatly I used Version 1.0.0 of vuelendar, as stated in the docs. After updating to 1.0.15 (I checked your package.json) it worked. Maybe the docs should be updated. Sorry for that. :)
