### ISSUE TITLE
How can i disable specific day?

### ISSUE THREAD

**Issue by PoojaJadav** [codesthq/vuelendar#37]
I want to disable a specific day. For example, Every Sunday must disable in the calendar.  Can we do it in this calendar?

**Comment by lusarz** [comment]
Hello @PoojaJadav, it is possible - the simplest way is to pass `isDisabled :Function` prop. This example should make every Sunday disabled:

```
<vl-day-selector
  :is-disabled="date => new Date(date).getDay() === 0"
  ...
/>  
```

**Comment by PoojaJadav** [comment]
*@Iusarz*, I need to disable all dates before the current date and also Sunday. `is-disabled` is not working with`disabled-dates`. Is there any other way to do it?

**Comment by PoojaJadav** [comment]
> *@Iusarz*, I need to disable all dates before the current date and also Sunday. `is-disabled` is not working with disabled-dates. Is there any other way to do it?

**Comment by lusarz** [comment]
@PoojaJadav Prefered way is to use only `is-disabled` and write whole logic inside it. `disabled-dates` will be depracated soon. Maybe something like that:

```
<vl-day-selector
  :is-disabled="date => (new Date(date).getTime() < new Date().getTime()) && (new Date(date).getDay() === 0)"
  ...
/>  
```

**Comment by PoojaJadav** [comment]
@lusarz Thanks :) Following code is working in my case: 

````
<vl-day-selector
      :is-disabled="date => (new Date(date).getTime() < new Date().getTime()) || (new Date(date).getDay() === 0)"
  ...
/>
````

**Comment by PoojaJadav** [comment]
What do you think if we manage`is-weekend-disable` flag in this package for weekend disable?

**Comment by lusarz** [comment]
We'd like to keep API of library as minimalistic as possible. You need to write it on your own:

```
<template>
  ...
  <vl-day-selector
      :is-disabled="isWeekend"
  />
  ...
/>
  ...
</template>



<script>
 export default {
  methods: {
    isWeekend (date) {
      // logic here
    }
  }
}
</script>
```
