### ISSUE TITLE
Config: first day of week

### ISSUE THREAD

**Issue by lusarz** [codesthq/vuelendar#4]
Make it possible to set first day of week

**Comment by lusarz** [comment]
@ValdoGhafoor, @wojciech-bak, @jsekulowicz 
What do you guys thinks about adding `firstDayOfWeek` property into [vl-range-selector](https://github.com/codesthq/vuelendar/blob/7d95417552b96aa62aa9d6107e175f4f26f63d19/components/vl-range-selector.vue#L19-L22) and [vl-day-selector](https://github.com/codesthq/vuelendar/blob/7d95417552b96aa62aa9d6107e175f4f26f63d19/components/vl-day-selector.vue#L22-L24) with type integer. Default value would be `0` - Monday (or maybe Sunday ? - I'm not sure ) is first day of week. 

When user pass value like:

    <vl-range-selector
       :first-day-of-week="1"
    /> 
he would get `Tuesday` as first day of week etc.

Or maybe you have another idea ?

**Comment by wojciech-bak** [comment]
Sounds like useful feature, but I'm not sure about integer type. For example, if `Monday = 0`, we're assuming that Monday is the first day of week.

Let's use some [Symbols](https://developer.mozilla.org/pl/docs/Web/JavaScript/Referencje/Obiekty/Symbol) like [here](https://stackoverflow.com/a/44447975) - then we'd be able to declare `:first-day-of-week="'monday'"`.

Another way I see is to use integer but not as "first day of week" but rather kind of translation `:translate-week="2"` from the default value (here: Monday + 2 = Wednesday).

**Comment by lusarz** [comment]
Okay, so let's do it in symbol/string way.

**Comment by omritelem** [comment]
Also have this issue.
Do you have an option to change the first day of the week? 
For example from - mon, tue, wed...
to - sun, mon, tue ?

Thanks!

**Comment by lusarz** [comment]
@omritelem I implemented support for [firstDayOfWeek](https://github.com/codesthq/vuelendar/blob/4ae82f49bbade0617745089dd461857264b554dc/components/vl-range-selector.vue#L37-L41) property with available options: [sun, mon, tue, wed, thu, fri, sat](https://github.com/codesthq/vuelendar/blob/4ae82f49bbade0617745089dd461857264b554dc/constants/days.js#L1). Let me know if everything works for you :)

**Comment by omritelem** [comment]
THANKS !!!
It was very fast!

I installed the library but got an error about the calendar/days..
something like that.

Does it work well for you? if yes, ill try this again on Sunday :)

Cheers!

**Comment by lusarz** [comment]
I confirm - there was issue with package published in npm, now it's fixed.
