### ISSUE TITLE
Config: disabled dates

### ISSUE THREAD

**Issue by lusarz** [codesthq/vuelendar#6]
Add `disabled: Array` to [vl-day-selector properties](https://github.com/codesthq/vuelendar/blob/3d54aa855ff6c2af2802342c77c6610c90c82dbc/components/vl-day-selector.vue#L22-L24) and setup it.

Example usage

    <vl-day-selector
      :disabled-dates="['2019-04-03', '2019-04-05']"
    />

**Comment by valdoryu** [comment]
Array is a good start, but I think it could be good to allow a range of dates as an object of the following forms to:

``` js
const disabledDates = {
  from: '2019-04-02',
  to: '2019-05-02'
}

// All dates will be disabled from 2nd April 2019 to 2nd May 2019
```
or

``` js
const disabledDates = {
  from: '2019-04-02',
}

// All dates will be disabled from 2nd April 2019 to the end of the world
```

or

``` js
const disabledDates = {
  to: '2019-04-02',
}

// All dates will be disabled from dinosaurs to 2nd April 2019
```


Use case for me is very clear: for example, for any kind of reservations, you want only future days to be selected. For birthdate, only past days should be selected

**Comment by lusarz** [comment]
Okay, so maybe we should support both types for `disabledDates` - `Array` and `Object` in `vl-day-selector` ? 

BTW What about `vl-range-selector` ? For me it may be a bit strange when user want to select for example `2019-04-05 - 2019-04-20`, and some date inside (like `2019-04-08`) would be disabled. I'd like to implement `disabledDates` support only for `vl-day-selector` for now.

**Comment by valdoryu** [comment]
Yes, both array and object should be supported.
I will start the PR today or tomorrow

I agree with you for ```vl-range-selector```, it will require some additional work that could be delayed until it's perfectly implemented on  ```vl-day-selector```

**Comment by valdoryu** [comment]
Check #11

**Comment by omritelem** [comment]
Also have this issue.

**Comment by lusarz** [comment]
@omritelem Could you tell more about your case ? I'll try help or improve implementation to support it :)

**Comment by omritelem** [comment]
Yes.
I am using v-range-selector element, and i want to use the options for date disabling, and its not working for me, with both options (Array and object) from documentation.

**Comment by lusarz** [comment]
@omritelem Documentation is a bit outdated currently. In your case I propose you to use [isDisabled](https://github.com/codesthq/vuelendar/blob/e9823309fa3116829cc49a372fa3d4ee559aeb17/components/vl-range-selector.vue#L32) function property. You can use it like:

    <vl-range-selector
      :is-disabled="date => date > '2018-05-03'"
    />

Let me know if it works for you.

**Comment by omritelem** [comment]
Hi, 
Thanks!
I installed the range-calendar-is-disabled branch and it helped solved the problem.

Will it be merged to master soon?

**Comment by lusarz** [comment]
It is actually merged to master. I've tested it our demo:

https://github.com/codesthq/vuelendar-demo/blob/eccf8e4c250943cb499589e3965ff580db879dfa/src/App.vue#L4-L9

And I see dates from July 2019 are disabled, to everything works as expected I think.

**Comment by lusarz** [comment]
We decided to remove `disabledDates` option. We encourage to use `isDisabled: Function` prop. 

@ValdoGhafoor Instead of passing `:disabled-dates="{ to: '2019-04-02' }"` it is possible to just pass: `is-disabled="date => date < '2019-04-02'"`
